### ISSUE TITLE
regions_buider.allow_ambiguous() doesn't prevent "ValueError: Multiple objects.."

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#174]
```
from shapely.geometry import box
warwick_box = regions_builder(request='warwick', level='city') \
    .where('warwick', within=box(-72, 41.5, -71, 42)) \
    .allow_ambiguous() \
    .build()
```
>ValueError: Multiple objects (2) were found for warwick:
>- Warwick (United States of America, Rhode Island)
>- West Warwick (United States of America, Rhode Island)

**Comment by IKupriyanov-HORIS** [comment]
It is expected behaviour. Use-case for `allow_ambiguous` is to ignore all ambiguous requests except ones with `where` invocation - requests, user trying to resolve (to make the process less noisy without requests we are not interested in, adding `where` and fixing ambiguity step by step).

In example bellow `springfield` will not cause ambiguity error, but `warwick` will.
```
regions_builder(request=['springfield', 'warwick'], level='city')\
    .where('warwick', within=box(-72, 41.5, -71, 42))\
    .allow_ambiguous()\
    .build()
```

**Comment by IKupriyanov-HORIS** [comment]
[Fixed](https://github.com/JetBrains/lets-plot/commit/a2107d97076b93ead8581560a15da87cd20d7fbf#diff-1da220bdec5d57408dfebf89b05a8c327c22aa2b2a56c3894469dc6371834df2)
