### ISSUE TITLE
Render non-interactive plot

### ISSUE THREAD

**Issue by ying-w** [JetBrains/lets-plot#228]
I'm trying to use github's built in ipynb capabilities to show a notebook with `lets-plot`

Unfortunately, the interactive plots that `let-plot` generates won't show up and instead you'd need to use nbviewer. This won't work for me since nbviewer [doesn't support private repos](https://github.com/jupyter/nbviewer/issues/294). (and I don't want to use the gist workaround)

My current workaround is to save plots with `ggsave()` but seems pretty clunky, is there a switch that can be turned on to disable the interactive plotting functionality?

**Comment by alshan** [comment]
Do I understand correctly that you are using Lets-Plot Kotlin API?

**Comment by ying-w** [comment]
I am using 'Lets-Plot for Python'

Here is an example of what I mean by lack of rendering. The quickstart example will render with nbviewer:

https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/quickstart.ipynb

However, the actual notebook won't render with github's default viewer

https://github.com/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/quickstart.ipynb

**Comment by alshan** [comment]
> I am using 'Lets-Plot for Python'

I was confused because 'ggsave()' is only available since yesterday's v1.5.3 release )

Anyways, theres is no API to do what you want so for now I only can offer a workaround involving calls to none-public methods, see cell 6 in this notebook: https://github.com/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks-dev/static_plot.ipynb

I think, none-js plots would be a useful option and we should add it in some of future builds. Thanks.

**Comment by alshan** [comment]
@ying-w good news: the 'No JS' mode is available in 1.5.5: https://github.com/JetBrains/lets-plot/tree/docs-1.5.5 : [No Javascript](https://github.com/JetBrains/lets-plot/blob/master/README_PYTHON.md#no-javascript-mode), give it a try!
