### ISSUE TITLE
Non-deterministic IDs for `clip-path` cause different svg outputs for the same input data

### ISSUE THREAD

**Issue by SerVB** [JetBrains/lets-plot#492]
Consider the following demo plot:

```kt
val p = letsPlot(emptyMap<String, List<Int>>()) + geomPoint()
ggsave(p, "demo-plot.svg", path = ".")
```

In the generated file, there are `clip-path="url(#soPGi5)"` and `<clipPath id="soPGi5">` parts. However, if we rerun the same code, the IDs will change.

I think lets-plot should generate deterministic output.

The current workaround is to manually find such IDs and replace them with deterministic ones, for example, like this:

```kt
fun makeDeterministicSvg(svgPath: Path) {
    var nextId = 0
    val randomToNumber = mutableMapOf<String, Int>()

    fun String.replaceAll(regex: String, format: String) = regex
        .toRegex()
        .replace(this) { res ->
            val (randomPart) = res.destructured
            val number = randomToNumber.getOrPut(randomPart) { nextId++ }
            val numberPart = "id$number"
            format.format(numberPart)
        }

    val deterministicText = svgPath
        .readText()
        .replaceAll(regex = """url\(#(\w{6})\)""", format = "url(#%s)")
        .replaceAll(regex = """id="(\w{6})"""", format = """id="%s"""")

    svgPath.writeText(deterministicText)
}
```

We've bumped into it in https://github.com/krzema12/kotlin-python/pull/90#discussion_r762468104

**Comment by krzema12** [comment]
Using constant seed for the random number generator should do the work, assuming that the rest of SVG generation is deterministic (e.g. order of evaluating the elements), and I don't see reasons why it shouldn't :)

**Comment by alshan** [comment]
Stable clippath id was a problem due to a weird situation when it must be unique across the entire document. As a document can contain multiple SVG plots generated independently, I can't see how to provide stable clippath id and guarantee no collisions at the same time.

For testing we use a workaround: https://github.com/JetBrains/lets-plot/blob/bdcb9948e5ba73cc69c06e34108eec0c5f04e128/plot-config-portable/src/commonTest/kotlin/plot/PlotSvgExportPortableTest.kt#L22

`SvgUID.setUpForTest()` substitutes a random id gen with an incremental (stable) one.

Would it work for you?

**Comment by SerVB** [comment]
Thanks, just checked it, works:
```kt
SvgUID.setUpForTest() 
val p = letsPlot(emptyMap<String, List<Int>>()) + geomPoint()
ggsave(p, "demo-plot.svg", path = ".")
```

Gives IDs like `clip-0`.

Probably this method can be renamed to something like `SvgUID.setUpDeterministic()` since it's useful not only for tests :)

Anyway, for us the issue is resolved. So feel free to close it when needed.
