### ISSUE TITLE
What plotting backends does lets-plot use?

### ISSUE THREAD

**Issue by amirhosseindavoody** [JetBrains/lets-plot#607]
I am trying to understand how performant this library would be when plotting big data sets (500k  ~ 1M data points per plot). I have found libraries that use javascript for rendering to be usually slow and I am trying to understand if lets-plot is intended for heavy data sets.

**Comment by alshan** [comment]
Lets-plot's JS code generates SVG image which then is rendered by the browser. So, plotting of all 1M points will be slow.

If you apply some sort of statistic (like bins or density [2d density](https://nbviewer.jupyter.org/github/JetBrains/lets-plot-docs/blob/master/source/examples/cookbook/density_2d.ipynb)) than it might work because statistics in lets-plot are applied on the backend, before data is sent to the browser.

Please note that on an attempt to plot "too mach" data lets-plot will apply some kind of [sampling](https://lets-plot.org/pages/sampling.html) (this can be overridden manually) to prevent freezing of the UI.

**Comment by amirhosseindavoody** [comment]
Thanks Igor for the explanation.
