### ISSUE TITLE
Support for ordered categoricals?

### ISSUE THREAD

**Issue by KarateSnowMachine** [JetBrains/lets-plot#914]
I'd like to say I'm really excited about this library and so far it has been working fantastically for me. 

I had one frustration around trying to reorder some facets that were not in alphabetical order. In other packages like `plotnine` an ordered categorical column in the pandas dataframe could be used to order the facet layout. However, I tried this with `lets-plot` and it seemed like it wasn't really paying attention to the ordering of categories (same thing for legend item ordering). I was just wondering whether there is support for ordered categoricals in `lets-plot` and I was just doing something wrong or if there is simply no support. If there is support, I can provide a minimal example. 

Thanks so much!

**Comment by alshan** [comment]
Hi, it turns out `order=0` option in facets is not handled properly. 

The following code is expected to preserve the B,C,A order of original sequence but in reality produces A,B,C sequence of facets:
```
data = dict(
    cat = ["B", "C", "A"],
    c = ["blue", "cyan", "gray"]
)

p = (ggplot(data) 
     + geom_point(aes(color="c"), size=15) 
     + scale_color_identity() 
     + theme_void() + ggsize(400, 200)
     + facet_wrap("cat", ncol=3, order=0)
    )
p
```
![image](https://github.com/JetBrains/lets-plot/assets/4430922/be432600-ed94-471d-a56a-3257eb98af9b)

---

But wait, there is more :) When saving this plot to PNG, the picture is correct!
```
ggsave(p, "facet_ordering_issue.png")
```
![image](https://github.com/JetBrains/lets-plot/assets/4430922/8817de4b-4bae-450c-9840-0953460042f1)

---

Saving plot to svg or pdf also produces picture with correct B,C,A order of facets.
However,  saving plot to html produces unexpected A,B,C ordering. 
Just amazing )

**Comment by nsiicm0** [comment]
In the past I had similar issues. Although the @KarateSnowMachine specifically asks for the feature to respect the dataframes categorical datatype for ordering, I was able to workaround this exact issue most of the time using as_discrete https://lets-plot.org/pages/api/lets_plot.mapping.as_discrete.html (leaving this here for future visitors - as I had a hard time finding this feature in the first place).

**Comment by alshan** [comment]
@nsiicm0 thank you for explanation. Indeed, my A,B,C example is about a different issue. I've extracted it as #923

**Comment by alshan** [comment]
Hi, added support for categoricals in [v4.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#added).

**Comment by KarateSnowMachine** [comment]
Thank you for this fix! 

I have grabbed the latest version and have confirmed I can use ordered categoricals for the axis labels with `as_discrete()` as well as with `facet_wrap(..., order=0)`
