### ISSUE TITLE
Stamen tiles have become blank

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#937]
Stamen map tiles have changed hosting, see [this page](https://maps.stamen.com/stadia-partnership/).

This has already affected the display of maps: instead of tails it says "Fail to fetch", see [here](https://lets-plot.org/pages/api/lets_plot.tilesets.STAMEN_DESIGN_TONER.html) or [here](https://datalore.jetbrains.com/report/static/HZqq77cegYd.E7get_WnChZ/05NSsbcsOYZMBN9n4JfKzL).

**Comment by alshan** [comment]
It seems we've cleaned up everywhere.

**Comment by alshan** [comment]
Hello @essicolo!  I hope you are good! 

To our utter dismay STAMEN has shutdown their free basemap tile hosting.
As a consequence of this unfortunate event one of our most favorite examples - ["Spatial prediction of soil pollutants with multi-output Gaussian processes"](https://nextjournal.com/essicolo/spatial-prediction-of-soil-pollutants-with-multi-output-gaussian-processes), is now partially broken.

A good news is that in Lets-Plot [v4.2.0](https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-420) we've added our own equivalent of STAMEN toner tiles. Please, take a look at our [clone of your notebook](https://nextjournal.com/asmirnov-horis/spatial-prediction-of-soil-pollutants-with-multi-output-gaussian-processes?token=26GT2sBa3Ycw6LGZxqdTay).

Would you mind to update our original notebook accordingly so that we could again use it as an example of geospatial analysis?
